import { Noto, montserrat } from "@/config/fonts";
import "@/styles/globals.css";
import { Providers } from "@/config/providers";
import MainNav from "@/components/main-nav";

export const metadata = {
  title: "Road To Reconnect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${Noto.variable} font-noto antialiased`}
      >
        <Providers>
          <MainNav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
